<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
    <IsPackable>false</IsPackable>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None
      Include="..\Duplicates\**\*.xaml"
      Link="UiSource\%(RecursiveDir)%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest" />
    <None
      Include="..\Duplicates\app.manifest"
      Link="UiSource\app.manifest"
      CopyToOutputDirectory="PreserveNewest" />
    <None
      Include="..\Duplicates\MainWindow.xaml.cs"
      Link="UiSource\MainWindow.xaml.cs"
      CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\Duplicates\Duplicates.csproj"
      ReferenceOutputAssembly="false"
      PrivateAssets="all"
      AdditionalProperties="DisableWindowsAppSdkAutoInitialize=true" />
    <ProjectReference Include="..\Duplicates.Engine\Duplicates.Engine.csproj" />
    <Reference Include="Duplicates">
      <HintPath>..\Duplicates\bin\$(Platform)\$(Configuration)\net10.0-windows10.0.22621.0\Duplicates.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.WinUI">
      <HintPath>..\Duplicates\bin\$(Platform)\$(Configuration)\net10.0-windows10.0.22621.0\Microsoft.WinUI.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="WinRT.Runtime">
      <HintPath>..\Duplicates\bin\$(Platform)\$(Configuration)\net10.0-windows10.0.22621.0\WinRT.Runtime.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
